name: da_bin_ich
timestamp: 1732491285
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1716537822
positions:
  aside: Aside
  sidebar: Sidebar
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  hero:
    hero-7488: 'Hero block'
  messages:
    system-messages-5737: 'System Messages'
  logo:
    logo-3502: 'Logo / Image'
    logo-3496: 'Logo / Image'
  menu:
    menu-5602: Menu
  social:
    social-1616: Social
  position:
    position-position-7828: Aside
    position-position-4165: Sidebar
  content:
    system-content-1909: 'Page Content'
  verticalmenu:
    verticalmenu-7236: 'Vertical Menu'
    verticalmenu-8984: 'Vertical Menu'
  contact:
    contact-7565: Contact
  totop:
    totop-1488: 'To Top'
  mobile-menu:
    mobile-menu-7772: Mobile-menu
inherit:
  default:
    navigation: navigation
    intro: intro
    features: features
    utility: utility
    above: above
    testimonials: testimonials
    expanded: expanded
    aside: aside
    mainbar: mainbar
    sidebar: sidebar
    footer: footer
    offcanvas: offcanvas
    system-messages-5737: system-messages-7972
    logo-3502: logo-9608
    menu-5602: menu-6409
    social-1616: social-3171
    position-position-7828: position-position-4734
    system-content-1909: system-content-1587
    position-position-4165: position-position-3949
    logo-3496: logo-9571
    verticalmenu-7236: verticalmenu-3628
    verticalmenu-8984: verticalmenu-6607
    contact-7565: contact-6866
    totop-1488: totop-8670
    mobile-menu-7772: mobile-menu-5697
