name: _error
timestamp: 1727904118
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1716537824
positions:
  header: Header
  breadcrumbs: Breadcrumbs
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-1265: Logo
  position:
    position-header: Header
    position-breadcrumbs: Breadcrumbs
    position-footer: Footer
  menu:
    menu-6387: Menu
  messages:
    system-messages-3702: 'System Messages'
  content:
    system-content-8039: 'Page Content'
  copyright:
    copyright-8214: Copyright
  spacer:
    spacer-9502: Spacer
  branding:
    branding-6124: Branding
  mobile-menu:
    mobile-menu-3952: Mobile-menu
inherit: {  }
