version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1716537824
layout:
  /header/:
    -
      - 'logo-1265 30'
      - 'position-header 70'
  /navigation/:
    -
      - menu-6387
  /main/:
    -
      - position-breadcrumbs
    -
      - system-messages-3702
    -
      - system-content-8039
  /footer/:
    -
      - position-footer
    -
      - 'copyright-8214 40'
      - 'spacer-9502 30'
      - 'branding-6124 30'
  offcanvas:
    -
      - mobile-menu-3952
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-header:
    attributes:
      key: header
  position-breadcrumbs:
    attributes:
      key: breadcrumbs
  position-footer:
    attributes:
      key: footer
