name: tierheimhilfe
timestamp: 1732491285
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1716537822
positions:
  aside: Aside
  sidebar: Sidebar
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  hero:
    hero-7488: 'Hero block'
  messages:
    system-messages-2472: 'System Messages'
  logo:
    logo-9941: 'Logo / Image'
    logo-9440: 'Logo / Image'
  menu:
    menu-6085: Menu
  social:
    social-6852: Social
  position:
    position-position-1808: Aside
    position-position-8677: Sidebar
  content:
    system-content-7795: 'Page Content'
  verticalmenu:
    verticalmenu-8168: 'Vertical Menu'
    verticalmenu-3086: 'Vertical Menu'
  contact:
    contact-4528: Contact
  totop:
    totop-5273: 'To Top'
  mobile-menu:
    mobile-menu-4956: Mobile-menu
inherit:
  default:
    navigation: navigation
    intro: intro
    features: features
    utility: utility
    above: above
    testimonials: testimonials
    expanded: expanded
    aside: aside
    mainbar: mainbar
    sidebar: sidebar
    footer: footer
    offcanvas: offcanvas
    system-messages-2472: system-messages-7972
    logo-9941: logo-9608
    menu-6085: menu-6409
    social-6852: social-3171
    position-position-1808: position-position-4734
    system-content-7795: system-content-1587
    position-position-8677: position-position-3949
    logo-9440: logo-9571
    verticalmenu-8168: verticalmenu-3628
    verticalmenu-3086: verticalmenu-6607
    contact-4528: contact-6866
    totop-5273: totop-8670
    mobile-menu-4956: mobile-menu-5697
