name: home_-_particles
timestamp: 1728593529
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1716537822
positions: {  }
sections:
  navigation: Navigation
  intro: Intro
  pricing: Pricing
  features: Features
  testimonials: Testimonials
  utility1: Utility1
  info: Info
  utility2: Utility2
  above: Above
  expanded: Expanded
  header: Header
  mainbar: Mainbar
  sidebar: Sidebar
  footer: Footer
  offcanvas: Offcanvas
particles:
  messages:
    system-messages-8010: 'System Messages'
  logo:
    logo-3240: 'Logo / Image'
    logo-6444: 'Logo / Image'
  menu:
    menu-1749: Menu
  social:
    social-6316: Social
  owlcarousel:
    owlcarousel-2455: 'Owl Carousel'
  2cols_w_image:
    2cols_w_image-5354: 'Two cols w/image'
  pricing:
    pricing-5306: Pricing
  contentcubes:
    contentcubes-6469: 'Content Cubes'
  testimonials_carousel:
    testimonials_carousel-4183: 'Testimonials Carousel'
  custom:
    custom-9685: 'Custom HTML'
    custom-9485: 'Custom HTML'
  content_repeater:
    content_repeater-7607: 'Content repeater'
  contenttabs:
    contenttabs-3854: 'Content Tabs'
  copyright:
    copyright-1352: Copyright
  horizontalmenu:
    horizontalmenu-4139: 'Horizontal Menu'
  totop:
    totop-1314: 'To Top'
  mobile-menu:
    mobile-menu-8964: Mobile-menu
inherit:
  default:
    navigation: navigation
    system-messages-8010: system-messages-7972
    logo-3240: logo-9608
    menu-1749: menu-6409
    social-6316: social-3171
    footer: footer
    logo-6444: logo-9571
    copyright-1352: copyright-1736
    horizontalmenu-4139: horizontalmenu-9034
    totop-1314: totop-8670
    offcanvas: offcanvas
    mobile-menu-8964: mobile-menu-5697
