name: home_-_particles
timestamp: 1728062952
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1716537822
positions: {  }
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  mainbar: Mainbar
  sidebar: Sidebar
  footer: Footer
  offcanvas: Offcanvas
particles:
  messages:
    system-messages-8010: 'System Messages'
  logo:
    logo-3240: 'Logo / Image'
    logo-6444: 'Logo / Image'
  menu:
    menu-1749: Menu
  social:
    social-6316: Social
  owlcarousel:
    owlcarousel-2455: 'Owl Carousel'
  custom:
    custom-5807: Intro
    custom-3119: Features
    custom-7658: 'Customer Testimonials'
    custom-6355: 'Develop CMS themes quickly'
  contenttabs:
    contenttabs-3854: 'Content Tabs'
  contentcubes:
    contentcubes-7850: 'Content Cubes'
  copyright:
    copyright-1352: Copyright
  horizontalmenu:
    horizontalmenu-4139: 'Horizontal Menu'
  totop:
    totop-1314: 'To Top'
  mobile-menu:
    mobile-menu-8964: Mobile-menu
inherit:
  default:
    navigation: navigation
    system-messages-8010: system-messages-7972
    logo-3240: logo-9608
    menu-1749: menu-6409
    social-6316: social-3171
    footer: footer
    logo-6444: logo-9571
    copyright-1352: copyright-1736
    horizontalmenu-4139: horizontalmenu-9034
    totop-1314: totop-8670
    offcanvas: offcanvas
    mobile-menu-8964: mobile-menu-5697
