name: home_-_particles
timestamp: 1732491285
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1716537822
positions: {  }
sections:
  navigation: Navigation
  intro: Intro
  pricing: Pricing
  features: Features
  testimonials: Testimonials
  utility1: Utility1
  info: Info
  utility2: Utility2
  above: Above
  expanded: Expanded
  header: Header
  mainbar: Mainbar
  sidebar: Sidebar
  footer: Footer
  offcanvas: Offcanvas
particles:
  owlcarousel:
    owlcarousel-2455: 'Owl Carousel'
  2cols_w_image:
    2cols_w_image-5354: 'Two cols w/image'
  pricing:
    pricing-5306: Pricing
  contentcubes:
    contentcubes-6469: 'Content Cubes'
  testimonials_carousel:
    testimonials_carousel-4183: 'Testimonials Carousel'
  custom:
    custom-9685: 'Custom HTML'
    custom-9485: 'Custom HTML'
  content_repeater:
    content_repeater-7607: 'Content repeater'
  contenttabs:
    contenttabs-3854: 'Content Tabs'
  messages:
    system-messages-8010: 'System Messages'
  logo:
    logo-3240: 'Logo / Image'
    logo-6444: 'Logo / Image'
  menu:
    menu-1749: Menu
  social:
    social-6316: Social
  verticalmenu:
    verticalmenu-5290: 'Vertical Menu'
    verticalmenu-9221: 'Vertical Menu'
  contact:
    contact-8278: Contact
  totop:
    totop-1314: 'To Top'
  mobile-menu:
    mobile-menu-8964: Mobile-menu
inherit:
  default:
    navigation: navigation
    expanded: expanded
    footer: footer
    offcanvas: offcanvas
    system-messages-8010: system-messages-7972
    logo-3240: logo-9608
    menu-1749: menu-6409
    social-6316: social-3171
    logo-6444: logo-9571
    verticalmenu-5290: verticalmenu-3628
    verticalmenu-9221: verticalmenu-6607
    contact-8278: contact-6866
    totop-1314: totop-8670
    mobile-menu-8964: mobile-menu-5697
