version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1716537822
layout:
  navigation: {  }
  /header/:
    -
      - owlcarousel-2455
  /intro/:
    -
      - 2cols_w_image-5354
  /pricing/:
    -
      - pricing-5306
  /features/:
    -
      - contentcubes-6469
  /testimonials/:
    -
      - testimonials_carousel-4183
  /utility1/:
    -
      - custom-9685
  /info/:
    -
      - content_repeater-7607
  /utility2/:
    -
      - custom-9485
  /above/: {  }
#  expanded:
#    -
#      - contenttabs-3854
  /container-main/:
    -
      -
        'mainbar 75': {  }
      -
        'sidebar 25': {  }
  expanded:
    -
      - contenttabs-3854
  footer: {  }
  offcanvas: {  }
structure:
  navigation:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  header:
    attributes:
      boxed: ''
      class: g-flushed
  intro:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
  pricing:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
  features:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
  testimonials:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
  utility1:
    type: section
    attributes:
      boxed: ''
      class: g-flushed
      variations: ''
  info:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
  utility2:
    type: section
    attributes:
      boxed: ''
      class: g-flushed
      variations: ''
  above:
    type: section
    attributes:
      boxed: ''
  expanded:
    type: section
    inherit:
      outline: default
      include:
        - attributes
  mainbar:
    type: section
    subtype: main
  sidebar:
    type: section
    subtype: aside
  container-main:
    attributes:
      boxed: ''
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - children
  offcanvas:
    inherit:
      outline: default
      include:
        - attributes
        - children
content:
  owlcarousel-2455:
    title: 'Owl Carousel'
    attributes:
      nav: enable
      imageOverlay: disable
      items:
        -
          class: ''
          image: 'gantry-media://owlcarousel/slide_01.png'
          line1: 'Dein Haustier verdient seinen eigenen'
          line2: 'Walk of Fame'
          link: '#g-expanded'
          linktext: 'Frag mich mal'
          disable: '0'
          name: 'Item 1'
        -
          class: ''
          image: 'gantry-media://owlcarousel/slide_02.png'
          line1: 'Dein Haustier verdient seinen eigenen'
          line2: 'Walk of Fame'
          link: '#g-expanded'
          linktext: 'Frag mich mal'
          disable: '0'
          name: 'Item 2'
        -
          class: ''
          image: 'gantry-media://owlcarousel/slide_03.png'
          line1: 'Dein Haustier verdient seinen eigenen'
          line2: 'Walk of Fame'
          link: '#g-expanded'
          linktext: 'Frag mich mal'
          disable: '0'
          name: 'Item 3'
        -
          class: ''
          image: 'gantry-media://owlcarousel/slide_04.png'
          line1: 'Dein Haustier verdient seinen eigenen'
          line2: 'Walk of Fame'
          link: '#g-expanded'
          linktext: 'Frag mich mal'
          disable: '0'
          name: 'Item 4'
        -
          class: ''
          image: 'gantry-media://owlcarousel/slide_05.png'
          line1: 'Dein Haustier verdient seinen eigenen'
          line2: 'Walk of Fame'
          link: '#g-expanded'
          linktext: 'Frag mich mal'
          disable: '0'
          name: 'Item 5'
  2cols_w_image-5354:
    title: 'Two cols w/image'
    attributes:
      image: 'gantry-media://mics/da-bin-ich.png'
      link: /da-bin-ich
      linktext: 'Da bin ich'
      description: 'Willkommen in der Welt, in der Ihr Liebling zum Superstar wird! Ich bin Julia - eine Fotografin und Hundefachfrau mit Erfahrung in der Erstellung fröhlicher und bunter Fotoshootings mit Ihren Haustieren. In meiner Arbeit ist das Wichtigste für mich das Wohlbefinden und die Freude Ihrer Lieblinge. Ich freue mich darauf, Sie in meinem Fotostudio in Werdohl oder kann zu Ihnen an jeden Ort in Nordrhein-Westfalen kommen und meine magischen Werkzeuge mitbringen. Lassen Sie Ihre Lieblinge eine Rolle in einem bunten Spektakel spielen! Und ich werde Ihnen helfen, begeisterte Zuschauer zu werden.'
  pricing-5306:
    attributes:
      link: /was-kostet
      linktext: 'Was kostet'
      prices:
        -
          image: 'gantry-media://pricing/studio.png'
          description: 'Kein Weg ist mir zu weit, um deinen pelzigen Gefährten ins beste Licht zu rücken. Meine mobile Ausrüstung bringt die Magie des Studios direkt zu dir nach Hause – für unvergessliche Bilder voller Liebe und Freude.'
          amount: '200'
          id: ''
          class: ''
          variations: ''
          title: Studio
        -
          image: 'gantry-media://pricing/momente.png'
          description: 'Natürliche Momente, unvergesslich festgehalten Ob im grünen Gras oder während des Lieblingsspiels – ich fange die Essenz deines Tieres in seiner gewohnten Umgebung ein. Authentisch und lebendig.'
          amount: '150'
          id: ''
          class: ''
          variations: ''
          title: Momente
        -
          image: 'gantry-media://pricing/reportage.png'
          description: 'Als stille Beobachterin halte ich die Highlights und die unbezahlbaren kleinen Momente deines besonderen Anlasses fest. Dein Event wird durch meine Linse lebendig und bleibt für immer in Erinnerung.'
          amount: '200'
          id: ''
          class: ''
          variations: ''
          title: Reportage
  contentcubes-6469:
    title: 'Content Cubes'
    attributes:
      css:
        class: ''
      title: Erfolg
      link: /erfolg
      items:
        -
          thumbnail: 'gantry-media://features/theater-machen-400x386.jpg'
          image: 'gantry-media://features/theater-machen.jpg'
          imageposition: left
          desc: 'Hier finden Sie eine Welt voller Emotionen, die in Momenten des Theaterspiels, der Lebensfreude und unerwarteten Momenten festgehalten werden. Jedes Bild erzählt seine eigene Geschichte, die mit dem Objektiv meiner Kamera aufgenommen wurde, und spiegelt die einzigartige Persönlichkeit und Schönheit unserer Begleittiere wider.'
          images:
            -
              thumbnail: 'gantry-media://features/erfolg-01-300x199.jpg'
              image: 'gantry-media://features/erfolg-01.jpg'
              alttext: Kanninchen
              text: 'New item'
            -
              thumbnail: 'gantry-media://features/erfolg-02-300x233.jpg'
              image: 'gantry-media://features/erfolg-02.jpg'
              text: 'New item'
            -
              thumbnail: 'gantry-media://features/erfolg-03-303x400.jpg'
              image: 'gantry-media://features/erfolg-03.jpg'
              text: 'New item'
          name: 'Theater machen'
        -
          thumbnail: 'gantry-media://features/lebhafte-400x265.jpg'
          image: 'gantry-media://features/lebhafte.jpg'
          imageposition: right
          desc: ''
          images:
            -
              thumbnail: 'gantry-media://features/erfolg-04-300x198.jpg'
              image: 'gantry-media://features/erfolg-04.jpg'
              alttext: ''
              text: 'New item'
            -
              thumbnail: 'gantry-media://features/erfolg-05-300x216.jpg'
              image: 'gantry-media://features/erfolg-05.jpg'
              alttext: ''
              text: 'New item'
          name: Lebhafte
        -
          thumbnail: 'gantry-media://features/erwischt-400x400.jpg'
          image: 'gantry-media://features/erwischt.jpg'
          imageposition: left
          desc: ''
          images:
            -
              thumbnail: 'gantry-media://features/erfolg-06-269x400.jpg'
              image: 'gantry-media://features/erfolg-06.jpg'
              alttext: ''
              text: 'New item'
            -
              thumbnail: 'gantry-media://features/erfolg-07-300x200.jpg'
              image: 'gantry-media://features/erfolg-07.jpg'
              alttext: ''
              text: 'New item'
          name: Erwischt
  testimonials_carousel-4183:
    title: 'Testimonials Carousel'
    attributes:
      title: 'Man über mich'
      link: /da-bin-ich/man-uber-mich/
      nav: enable
      imageOverlay: disable
      items:
        -
          class: ''
          image: 'gantry-media://testimonials/testimonial1.jpg'
          date: 10.02.2024
          desc: 'Überwältigt von der Hundefotografin Julia: Ihre Bilder sind wahre Kunst, die Seelen meiner zwei Hunde und meines Katers einfangen. Mit Talent, Leidenschaft und einem Auge fürs Detail macht sie jede Session einzigartig. Unvergessliche Erinnerungen, absolut empfehlenswert!'
          link: 'https://www.instagram.com/kinolog.lapki.nrw'
          linktext: '@kinolog.lapki.nrw'
          disable: '0'
          name: 'Olesya Poruchnyk'
        -
          class: ''
          image: 'gantry-media://testimonials/testimonial2.jpg'
          date: 17.10.2023
          desc: 'Hallo, danke für unsere Fotos mit Lunochka 😍 Die Aufnahmen sind so lebendig geworden, mir hat alles sehr gefallen, man sieht, dass es Ihnen viel Freude bereitet und man spürt neben Ihrem Professionalismus auch eine große Liebe zu Tieren ☺️ Ich erinnere mich, wie Sie damals noch mit einem Gips am Bein gearbeitet haben, aber das hat Sie nicht davon abgehalten, die schönsten und erfolgreichsten Aufnahmen von Luna und den anderen Hunden zu machen 🙈😍 Ich bewundere Ihren Beruf, Sie machen Hundebesitzer glücklicher 🥰 Ich wünsche Ihnen mehr Ideen und mehr Möglichkeiten zu deren Umsetzung 🙏🏻☺️'
          link: 'https://www.instagram.com/promama_lera'
          linktext: '@promama_lera'
          disable: '0'
          name: promama_lera
        -
          class: ''
          image: 'gantry-media://testimonials/testimonial3.jpg'
          date: 28.03.2024
          desc: 'Liebe Julia hat uns heute besucht! Sie kam zu uns nach Hause und machte Fotos mit meinen Kaninchen. Zuerst hat sie alle ihre Sachen für das Shooting mitgebracht und dann haben wir alles an seinen Platz gebracht. Es ist sehr lustig, wie viele interessante Dinge sie dabei hatte. Unterschiedliche Hintergründe und allerlei Kleinigkeiten. Wir haben verschiedene Motive ausprobiert, es war toll, die Kaninchen spielten die Hauptrolle und es hat sogar Spaß gemacht. Sehr einfühlsame und nette Fotografin! Wir freuen uns darauf, Julia wiederzusehen!'
          link: 'https://www.instagram.com/vomhoennetal'
          linktext: '@vomhoennetal'
          disable: '0'
          name: vomhoennetal
        -
          class: ''
          image: 'gantry-media://testimonials/testimonial4.jpg'
          date: 29.09.2024
          desc: 'Ich bin absolut begeistert von der Hundefotografin Julia, die schon seit einiger Zeit die besonderen Momente unserer vierbeinigen Freunde festhält. Ihre Arbeit ist einfach beeindruckend und hat mir persönlich sehr geholfen. Die Fotos, die sie macht, sind mehr als nur Bilder – sie sind echte Kunstwerke, die Persönlichkeit und die einzigartigen Charakterzüge jedes Hundes einfangen. Besonders während der Gruppenstunden in unserer Hundeschule Lapki in Mettmann beweist sie immer wieder aufs Neue ihr außergewöhnliches Talent und Gespür für den richtigen Moment. Jedes Mal, wenn sie bei uns ist, freue ich mich schon auf die wunderbaren Fotos, die entstehen. Sie hat nicht nur ein gutes Auge für die besonderen Momente, sondern versteht es auch, eine entspannte Atmosphäre zu schaffen, in der sich sowohl Hunde...'
          link: 'https://lapki.nrw'
          linktext: 'Hundeschule Lapki'
          disable: '0'
          name: 'Hundeschule Lapki'
  custom-9685:
    title: 'Custom HTML'
    attributes:
      html: "<div class=\"g-grid\">\n\t<div class=\"g-block ticket\">\n\t\t<div class=\"g-content center p-2\">\n\t\t\t<div class=\"heading heading-2xlarge\">100%</div>\n\t\t\t<div class=\"heading heading-large\">Rabatt</div>\n\t\t</div>\n\t</div>\n\t<div class=\"g-block d-flex align-items-center\">\n\t\t<div class=\"g-content p-2\">\n\t\t\t<div class=\"heading heading-medium mb-2\">Ein beliebiges Fotoshooting für Dein aus dem Tierheim adoptiertes Tier</div>\n\t\t<a href=\"#g-expanded\" class=\"button\">Frag mich mal</a>\n\t\t</div>\n\t</div>\n</div>"
  content_repeater-7607:
    title: 'Content repeater'
    attributes:
      title: Tierheimhilfe
      link: /tierheimhilfe
      content:
        -
          class: ''
          name: ''
          image: 'gantry-media://mics/tierheimhilfe.png'
          imagealt: Tierheimhilfe
          date: ''
          desc: 'Ich finde es wichtig, mein Herz und meine Fähigkeiten für einen guten Zweck einzusetzen. Deshalb verbringe ich auch Zeit als Freiwilliger in Tierheimen – fotografiere die Schützlinge, spiele mit den Katzen, gehe mit den Hunden spazieren und reinige die Käfige. Einen Teil der Einnahmen spende ich ebenfalls an die Tierheime. Meine Kunden entscheiden selbst, welchem Tierheim das Geld zugutekommt. Gemeinsam leisten wir einen Beitrag zur Unterstützung bedürftiger Tiere.'
          link: /tierheimhilfe
          linktext: 'Mehr sehen'
          disable: '0'
          title: 'New item'
  custom-9485:
    title: 'Custom HTML'
    attributes:
      html: "<div class=\"g-grid\">\n\t<div class=\"g-block size-100 center ticket\">\n\t\t<div class=\"g-content\">\n\t\t\t<div class=\"heading heading-xlarge\">50% Rabatt</div>\n\t\t</div>\n\t</div>\n\t<div class=\"g-block size-100\">\n\t\t<div class=\"g-grid\">\n\t\t\t<div class=\"g-block d-flex justify-content-center align-items-center p-2\">\n\t\t\t\t<div class=\"heading heading-medium align-right\">beim Fotoshootings am Geburtstag Deines Tieres</div>\n\t\t\t</div>\n\t\t\t<div class=\"g-block d-flex justify-content-center align-items-center\">\n\t\t\t\t<a href=\"#g-expanded\" class=\"button\">Frag mich mal</a>\n\t\t\t</div>\n\t\t</div>\n\t</div>\n</div>"
  contenttabs-3854:
    title: 'Content Tabs'
    attributes:
      title: Kontaktformular
      link: /kontakt
      desc: "<p>Möchten Sie ein besonderes Fotoshooting organisieren oder einfach mehr erfahren? Erzählen Sie mir, wen Sie auf den Fotos sehen möchten — Ihre süßen Haustiere und welche genau, alleine oder mit ihren Lieblingsmenschen. Vergessen Sie nicht anzugeben, wo Sie leben und welche Zeit Ihnen am besten passt. Haben Sie besondere Wünsche oder Ideen für das Thema des Shootings?</p>\n\n<p>Dies ist nur eine Informationsanfrage, die Sie zu nichts weiter verpflichtet. Ich freue mich darauf, mehr über Ihre Wünsche zu erfahren und die Details Ihrer einzigartigen Fotosession zu besprechen!</p>\n\n<p>* zeigt erforderliche Felder an</p>"
      image: 'gantry-media://mics/kontaktformular.png'
      items:
        -
          content: '[contact-form-7 id="cfd3b56" title="Kontaktformular"]'
          title: 'Anfrage zur dein Tierfotografin'
        -
          content: '<div>Coming soon</div>'
          title: 'Anfrage fürdein Fotoshooting'
