name: _body_only
timestamp: 1727904118
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1716537824
positions:
  header: Header
  breadcrumbs: Breadcrumbs
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-3296: Logo
  position:
    position-header: Header
    position-breadcrumbs: Breadcrumbs
    position-footer: Footer
  menu:
    menu-8511: Menu
  messages:
    system-messages-3696: 'System Messages'
  content:
    system-content-7132: 'Page Content'
  copyright:
    copyright-7023: Copyright
  spacer:
    spacer-3849: Spacer
  branding:
    branding-2430: Branding
  mobile-menu:
    mobile-menu-5307: Mobile-menu
inherit: {  }
