name: memoiren
timestamp: 1732491285
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1716537822
positions:
  aside: Aside
  sidebar: Sidebar
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  aside: Aside
  sidebar: Sidebar
  mainbar: Mainbar
  footer: Footer
  offcanvas: Offcanvas
particles:
  hero:
    hero-7488: 'Hero block'
  messages:
    system-messages-5361: 'System Messages'
  logo:
    logo-6314: 'Logo / Image'
    logo-7826: 'Logo / Image'
  menu:
    menu-9380: Menu
  social:
    social-6120: Social
  position:
    position-position-1840: Aside
    position-position-6569: Sidebar
  content:
    system-content-3719: 'Page Content'
  verticalmenu:
    verticalmenu-7394: 'Vertical Menu'
    verticalmenu-9164: 'Vertical Menu'
  contact:
    contact-2213: Contact
  totop:
    totop-2919: 'To Top'
  mobile-menu:
    mobile-menu-8763: Mobile-menu
inherit:
  default:
    navigation: navigation
    intro: intro
    features: features
    utility: utility
    above: above
    testimonials: testimonials
    expanded: expanded
    aside: aside
    mainbar: mainbar
    sidebar: sidebar
    footer: footer
    offcanvas: offcanvas
    system-messages-5361: system-messages-7972
    logo-6314: logo-9608
    menu-9380: menu-6409
    social-6120: social-3171
    position-position-1840: position-position-4734
    system-content-3719: system-content-1587
    position-position-6569: position-position-3949
    logo-7826: logo-9571
    verticalmenu-7394: verticalmenu-3628
    verticalmenu-9164: verticalmenu-6607
    contact-2213: contact-6866
    totop-2919: totop-8670
    mobile-menu-8763: mobile-menu-5697
