name: home
timestamp: 1728059045
version: 7
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: home
  timestamp: 1716537824
positions:
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  showcase: Showcase
  feature: Feature
  subfeature: Subfeature
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-1082: 'Logo / Image'
  menu:
    menu-4893: Menu
  sample:
    sample-1: 'Gantry 5'
    sample-2: 'Getting Started'
    sample-3: 'Key Features'
  messages:
    system-messages-3480: 'System Messages'
  position:
    position-footer: Footer
  copyright:
    copyright-7500: Copyright
  social:
    social-2990: Social
  branding:
    branding-3794: Branding
  mobile-menu:
    mobile-menu-5819: 'Mobile Menu'
inherit: {  }
