name: home_-_backup
timestamp: 1732491285
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1716537822
positions: {  }
sections:
  navigation: Navigation
  intro: Intro
  features: Features
  utility: Utility
  above: Above
  testimonials: Testimonials
  expanded: Expanded
  header: Header
  mainbar: Mainbar
  sidebar: Sidebar
  footer: Footer
  offcanvas: Offcanvas
particles:
  owlcarousel:
    owlcarousel-2455: 'Owl Carousel'
  custom:
    custom-5807: Intro
    custom-3119: Features
    custom-7658: 'Customer Testimonials'
    custom-6355: 'Develop CMS themes quickly'
  contenttabs:
    contenttabs-3854: 'Content Tabs'
  contentcubes:
    contentcubes-7850: 'Content Cubes'
  messages:
    system-messages-4741: 'System Messages'
  logo:
    logo-2399: 'Logo / Image'
    logo-4350: 'Logo / Image'
  menu:
    menu-2185: Menu
  social:
    social-8734: Social
  verticalmenu:
    verticalmenu-7948: 'Vertical Menu'
    verticalmenu-6922: 'Vertical Menu'
  contact:
    contact-1311: Contact
  totop:
    totop-4588: 'To Top'
  mobile-menu:
    mobile-menu-4582: Mobile-menu
inherit:
  default:
    navigation: navigation
    footer: footer
    offcanvas: offcanvas
    system-messages-4741: system-messages-7972
    logo-2399: logo-9608
    menu-2185: menu-6409
    social-8734: social-3171
    logo-4350: logo-9571
    verticalmenu-7948: verticalmenu-3628
    verticalmenu-6922: verticalmenu-6607
    contact-1311: contact-6866
    totop-4588: totop-8670
    mobile-menu-4582: mobile-menu-5697
